### PR TITLE
Adding Lucario by @raphamorim

### PR DESCRIPTION
**Pull request by christopher-kapic**
This is my first time submitting a pull request, so I apologize if there is any standard practice that I don't know to follow. Hopefully this is useful!

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Thanks for the PR!

For some reason, Travis CI doesn't run. Could you please push an empty commit trigger CI?

Apart from that, lgtm.

**Comment by christopher-kapic** [comment]
I'm guessing that means just run `git commit --allow-empty -m "trigger Cl"`?

**Comment by RunDevelopment** [comment]
Yes.

**Comment by RunDevelopment** [comment]
12 minutes to start a 5s test with Travis... I know why we switched to GH Actions everywhere else.

Sorry for the wait @christopher-kapic!

**Review by RunDevelopment — APPROVED** [review]

**Comment by christopher-kapic** [comment]
Thanks @RunDevelopment !

**Pull request merged**
