### PR TITLE
Improve VS Code Dark Plus theme accuracy

### PR DESCRIPTION
**Pull request by karlhorky**
Hi, a quick fix for a number of color inaccuracies in the VS Code Dark Plus theme.

Try out the theme switcher dropdown on the website below for a detailed overview of the changes:

Website: https://objective-williams-02e373.netlify.app/
Repo: https://github.com/karlhorky/prismjs-vs-code-dark-theme-fix

Preview (may be outdated):

### Old

Screen Shot 2020-08-26 at 17 56 17

### New

Screen Shot 2020-08-27 at 21 25 29

### CODE REVIEW

**Comment by RunDevelopment** [comment]
That looks really good!

Could you please run the `npx gulp screenshot` command to update the screenshot? After that, we can merge this.

---

Also, you might be interested to know that Prism also has a regex language that will add itself to JS, JSX, TS, and TSX. I gave it [_some_ highlighting a while ago](https://github.com/PrismJS/prism/pull/2325) but it's far from ideal.

Also also, should I add an alias for control-flow keywords (e.g. `if`, `else`, `try`, `return`, aka the purple ones) to JS Extras?

**Comment by karlhorky** [comment]
> Also also, should I add an alias for control-flow keywords (e.g. if, else, try, return, aka the purple ones) to JS Extras?

That would be great, cheers! This along with https://github.com/PrismJS/prism/issues/2528 would probably cover a lot of the remaining missing things.

> Prism also has a regex language that will add itself to JS, JSX, TS, and TSX

Added to the demo, thanks! I also added a new escape token color.

> Could you please run the `npx gulp screenshot` command to update the screenshot?

Sure, done!

**Comment by karlhorky** [comment]
Also styled the `.token.keyword.control-flow` classes: 6449e45151d8aad735d1035a3d214764c9d17f61

**Comment by karlhorky** [comment]
@RunDevelopment Added the color changes from `.token.imports .token.maybe-class-name` and `.token.exports .token.maybe-class-name` (https://github.com/PrismJS/prism/issues/2528 and https://github.com/PrismJS/prism/pull/2533).

I guess this PR is now ready to go?

**Review by RunDevelopment — APPROVED** [review]

**Comment by RunDevelopment** [comment]
Thank you for contributing @karlhorky!

**Comment by karlhorky** [comment]
Glad to help! Thanks for the merge and your tireless work on this!! 💯

**Comment by karlhorky** [comment]
@RunDevelopment would it be possible to get a new version published to npm with these changes? Version `1.4.0` does not have them...

**Comment by RunDevelopment** [comment]
@mAAdhaTTah Could you please handle the release? The next version will be `1.4.1`, I think.

**Comment by mAAdhaTTah** [comment]
@RunDevelopment @karlhorky done. `v1.4.1` is live in npm.

**Comment by karlhorky** [comment]
Thanks @RunDevelopment @mAAdhaTTah !

**Pull request merged**
