### PR TITLE
Use Github Actions

### PR DESCRIPTION
**Pull request by RunDevelopment**
Dropped Travis in favor of Github Actions. The CI setup here is now the same as in PrismJS/prism.

I also the same badges as in PrismJS/prism readme.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
[More motivation](https://github.com/PrismJS/prism-themes/pull/112#issuecomment-793167734).

**Comment by mAAdhaTTah** [comment]
1. Any idea why the tests didn't run on this PR?
2. I'm not opposed to the test matrix but given we're just linting CSS (rather than unit testing a js lib), maybe we only need the latest version?

**Comment by RunDevelopment** [comment]
1. Nope. I don't understand why it didn't run either.
2. Good catch. I just copied the thing over from PrismJS/prism. I'll change it.

**Comment by mAAdhaTTah** [comment]
Oh probably cuz it's from a fork.

**Review by mAAdhaTTah — APPROVED** [review]

**Comment by RunDevelopment** [comment]
> probably cuz it's from a fork.

That's also my guess. Let's see if it'll work :)

**Comment by RunDevelopment** [comment]
Haha, [it worked](https://github.com/PrismJS/prism-themes/actions/runs/652581138)!

**Comment by RunDevelopment** [comment]
Ah.... The workflow works but the test fails. Give me a minute...

**Comment by RunDevelopment** [comment]
It works now.

**Pull request merged**
