### PR TITLE
fix first line being indented slightly.

### PR DESCRIPTION
**Pull request by CarlVitasa**

### CODE REVIEW

**Comment by RunDevelopment** [comment]
@CarlVitasa Thank you for the PR!

Unfortunately, I cannot see what problem this PR is trying to solve, not do I see how it solves the problem I assume it's trying to solve. Please explain the problem you encountered with this theme and how your PR solves this problem.

**Comment by CarlVitasa** [comment]
Currently there is a space added on the first line of code when using the nord theme: 
image

After setting `padding: 0em` this is what it looks like:
image

**Comment by RunDevelopment** [comment]
This space is not present in our auto-generate screenshots, so it seems to me that the theme itself isn't at fault here. 

I also tried using Nord on Prism's website, and there is no space either:

image

I think the problem lies with some other style of your website also applying to code blocks. Could you please provide a reproducible example or a link to a website with your issue?

**Comment by CarlVitasa** [comment]
I've just reviewed on my end and the culprit was another stylesheet overriding the `code` element.

**Pull request closed without merging**
