### PR TITLE
Hello Panda🐼 to Prism

### PR DESCRIPTION
**Pull request by siamak**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Please look at the other themes and include a preview.

**Comment by mAAdhaTTah** [comment]
@siamak Since this PR is old / stale, I'm going to close, but if you're still interested in merging this theme into `prism-themes`, we'd need you to add a screenshot to the PR. You can reopen the PR then and we'd be happy to accept.

**Comment by krry** [comment]
This makes me a sad 🐼 

I'm enjoying the Panda of late, so I'll gladly make this happen unless someone has already?

**Comment by mAAdhaTTah** [comment]
@krry No one has picked this up, so you're welcome to make it happen.

**Comment by krry** [comment]
Cool. Made the requisite screenshot. Seeing also that there has been some wobble in the Panda style from Atom to VSCode, and that this PR may be more in the old vein. Do we reopen and complete this one with the screenshot? Or make a new PR and aim for the latest Panda?

**Comment by RunDevelopment** [comment]
The easiest way to proceed would be to take the CSS from this PR and use it as the base for a new PR. We added stylelint and some other stuff since this PR was opened, so our tools will say something.

**Pull request closed without merging**
